// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID      int64 `json:"id"`
	Balance int32 `json:"balance"`
}

type Address struct {
	ID       int64  `json:"id"`
	City     string `json:"city"`
	Line1    string `json:"line1"`
	Line2    string `json:"line2"`
	Postcode string `json:"postcode"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
	Token     string    `json:"token"`
	UserAgent string    `json:"user_agent"`
	ClientIp  string    `json:"client_ip"`
	IsBlocked bool      `json:"is_blocked"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID             int64         `json:"id"`
	Username       string        `json:"username"`
	FirstName      string        `json:"first_name"`
	SecondName     string        `json:"second_name"`
	Email          string        `json:"email"`
	EmailConfirm   bool          `json:"email_confirm"`
	Roles          []string      `json:"roles"`
	HashedPassword string        `json:"hashed_password"`
	Account        sql.NullInt64 `json:"account"`
	Address        sql.NullInt64 `json:"address"`
	CreatedAt      time.Time     `json:"created_at"`
}
