// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAccBalance(ctx context.Context, arg AddAccBalanceParams) (Account, error)
	ChangePassword(ctx context.Context, arg ChangePasswordParams) (User, error)
	CreateAccount(ctx context.Context, balance int32) (Account, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteAddress(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, email string) error
	EmailConfirmd(ctx context.Context, arg EmailConfirmdParams) (User, error)
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetAddressForUpdate(ctx context.Context, id int64) (Address, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, email string) (User, error)
	GetUserAccount(ctx context.Context, id int64) (Account, error)
	GetUserAddress(ctx context.Context, id int64) (Address, error)
	GetUserForUpdate(ctx context.Context, email string) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListAddresses(ctx context.Context, arg ListAddressesParams) ([]Address, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SubAccBalance(ctx context.Context, arg SubAccBalanceParams) (Account, error)
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
}

var _ Querier = (*Queries)(nil)
